#!/usr/bin/env/ python

import requests
from bs4 import BeautifulSoup

mess = ["Blues from a Gun" 
"House" 
"Cuts You Up" 
"Nothing Compares 2 U" 
"Blue Sky Mine" 
"Metropolis" 
"Enjoy the Silence" 
"The Emperor's New Clothes" 
"Forgotten Years" 
"Here's Where the Story Ends" 
"Policy of Truth" 
"Way Down Now" 
"Joey" 
"Jealous" 
"I'll Be Your Chauffeur" 
"Jealous^" 
"Stop!" 
"Every Beat of the Heart" 
"Stop!^"
"Suicide Blonde" 
"Never Enough" 
"Merry Go Round" 
"Never Enough^" 
"Been Caught Stealing" 
"Merry Go Round^" 
"Been Caught Stealing^" 
"More" 
"Kinky Afro" 
"All This Time" 
"Right Here, Right Now" 
"Losing My Religion" 
"See the Lights" 
"The Other Side of Summer" 
"Get the Message" 
"Kiss Them for Me" 
"Rush" 
"Until She Comes" 
"So You Think You're in Love" 
"Give It Away" 
"The Fly" 
"Smells Like Teen Spirit" 
"Mysterious Ways" 
"Sax and Violins" 
"What's Good" 
"Hit" 
"One" 
"High" 
"Teen Angst (What the World Needs Now)" 
"Weirdo" 
"The Ballad of Peter Pumpkinhead" 
"Friday I'm in Love" 
"Good Stuff" 
"Midlife Crisis" 
"Tomorrow" 
"Digging in the Dirt" 
"Blood Makes Noise" 
"Drive" 
"These Are Days" 
"Somebody to Shove" 
"Steam" 
"Not Sleeping Around" 
"The Devil You Know" 
"Feed the Tree" 
"I Feel You" 
"Regret" 
"Walking in My Shoes" 
"Regret^"
"Pets" 
"Break It Down Again" 
"Soul to Squeeze" 
"My Sister" 
"No Rain" 
"Soul to Squeeze^" 
"No Rain^" 
"Heart-Shaped Box" 
"Into Your Arms" 
"Daughter" 
"Found Out About You" 
"All Apologies" 
"Loser" 
"Mmm Mmm Mmm Mmm" 
"God" 
"The More You Ignore Me, the Closer I Get" 
"Selling the Drama" 
"Longview" 
"Fall Down" 
"Come Out and Play" 
"Einstein on the Beach (For an Eggman)" 
"Basket Case" 
"What's the Frequency, Kenneth?" 
"Zombie" 
"About a Girl" 
"Bang and Blame" 
"When I Come Around" 
"Lightning Crashes" 
"Good" 
"Misery" 
"Hold Me, Thrill Me, Kiss Me, Kill Me" 
"You Oughta Know" 
"J.A.R." 
"Tomorrow" 
"Comedown" 
"Name" 
"Hand in My Pocket" 
"Lump" 
"Name^"
"My Friends" 
"Glycerine" 
"Wonderwall" 
"1979" 
"Wonderwall^"
"Ironic" 
"Champagne Supernova" 
"Salvation" 
"Mother Mother" 
"Counting Blue Cars" 
"Pepper"
"Standing Outside a Broken Phone Booth with Money in My Hand" 
"Who You Are" 
"Down" 
"Novocaine for the Soul" 
"What I Got" 
"Swallowed" 
"#1 Crush" 
"Discothèque" 
"Lakini's Juice" 
"One Headlight" 
"Staring at the Sun" 
"The Freshmen" 
"Semi-Charmed Life"
"The Impression That I Get" 
"Semi-Charmed Life^" 
"Push" 
"Fly" 
"Walkin' on the Sun" 
"Tubthumping" 
"Everything to Everyone" 
"Sex and Candy"
"The Way" 
"Closing Time" 
"Iris" 
"Inside Out" 
"One Week" 
"Inside Out^" 
"One Week^" 
"Inside Out^"
"Celebrity Skin" 
"Slide" 
"Celebrity Skin^" 
"Slide^"  
"Fly Away" 
"Never There" 
"What It's Like" 
"Every Morning" 
"What It's Like^" 
"Every Morning^" 
"My Own Worst Enemy"
"Scar Tissue" 
"Higher" 
"The Chemicals Between Us" 
"Learn to Fly" 
"The Chemicals Between Us^" 
"Higher^" 
"The Chemicals Between Us^" 
"Higher^" 
"Re-Arranged" 
"All the Small Things" ]

lessmess = str(mess.replace("\n",","))

print(lessmess)